# Generated by Django 4.2.7 on 2025-09-25 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing_templates', '0001_initial'),
        ('config_generator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedconfig',
            name='bandwidth_mbps',
            field=models.PositiveIntegerField(blank=True, help_text='Bandwidth in Mbps from billing template', null=True),
        ),
        migrations.AddField(
            model_name='generatedconfig',
            name='billing_template',
            field=models.ForeignKey(blank=True, help_text='Billing template used for this configuration', null=True, on_delete=django.db.models.deletion.CASCADE, to='billing_templates.billingtemplate'),
        ),
        migrations.AddField(
            model_name='generatedconfig',
            name='duration_seconds',
            field=models.PositiveIntegerField(blank=True, help_text='Duration in seconds from billing template', null=True),
        ),
        migrations.AddField(
            model_name='generatedconfig',
            name='upload_mbps',
            field=models.PositiveIntegerField(blank=True, help_text='Upload bandwidth in Mbps from billing template', null=True),
        ),
    ]
