# Generated by Django 4.2.7 on 2025-09-25 10:00

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('config_generator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Template name (e.g., 'Basic Daily Plan')", max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description of the billing template')),
                ('mbps', models.PositiveIntegerField(help_text='Bandwidth in Mbps', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)])),
                ('upload_mbps', models.PositiveIntegerField(blank=True, help_text='Upload bandwidth in Mbps (optional, defaults to download speed)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)])),
                ('duration_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('hourly', 'Hourly')], default='daily', help_text='Duration type (daily, weekly, monthly, hourly)', max_length=20)),
                ('duration_value', models.PositiveIntegerField(default=1, help_text='Duration value (e.g., 1 for 1 day, 7 for 7 days)')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in KES', max_digits=10)),
                ('currency', models.CharField(default='KES', help_text='Currency code', max_length=3)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this template is active')),
                ('is_popular', models.BooleanField(default=False, help_text='Mark as popular plan')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Sort order for display')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Admin who created this template', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Billing Template',
                'verbose_name_plural': 'Billing Templates',
                'ordering': ['sort_order', 'price'],
            },
        ),
        migrations.CreateModel(
            name='BillingTemplateCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(default='#3B82F6', help_text='Hex color code for category display', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Billing Template Category',
                'verbose_name_plural': 'Billing Template Categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BillingTemplateUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('generated_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_template_usage', to='config_generator.generatedconfig')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_records', to='billing_templates.billingtemplate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_template_usage', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Billing Template Usage',
                'verbose_name_plural': 'Billing Template Usage Records',
                'ordering': ['-used_at'],
            },
        ),
        migrations.CreateModel(
            name='BillingTemplateCategoryAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_assignments', to='billing_templates.billingtemplatecategory')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_assignments', to='billing_templates.billingtemplate')),
            ],
            options={
                'verbose_name': 'Template Category Assignment',
                'verbose_name_plural': 'Template Category Assignments',
                'unique_together': {('template', 'category')},
            },
        ),
    ]
