# Generated by Django 4.2.7 on 2025-09-28 01:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20250928_0059'),
    ]

    operations = [
        # Empty migration - Cashier model will be added later
        # This ensures the migration sequence works without foreign key issues
    ]