# Generated by Django 4.2.7 on 2025-09-27 22:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='callback_url',
            field=models.URLField(blank=True, help_text='Auto-generated callback URL for this provider', null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='mpesa_consumer_key',
            field=models.TextField(blank=True, help_text='M-PESA Daraja API Consumer Key (encrypted)', null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='mpesa_consumer_secret',
            field=models.TextField(blank=True, help_text='M-PESA Daraja API Consumer Secret (encrypted)', null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='mpesa_credentials_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='provider',
            name='mpesa_environment',
            field=models.CharField(choices=[('sandbox', 'Sandbox'), ('production', 'Production')], default='sandbox', max_length=10),
        ),
        migrations.AddField(
            model_name='provider',
            name='mpesa_last_test',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='mpesa_passkey',
            field=models.TextField(blank=True, help_text='M-PESA Daraja API Passkey (encrypted)', null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='mpesa_shortcode',
            field=models.CharField(blank=True, help_text='M-PESA Paybill/Till Number', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='mpesa_test_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='Cashier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended')], default='active', max_length=20)),
                ('can_generate_tickets', models.BooleanField(default=True)),
                ('can_sell_tickets', models.BooleanField(default=True)),
                ('can_view_sales', models.BooleanField(default=False)),
                ('can_manage_users', models.BooleanField(default=False)),
                ('can_download_configs', models.BooleanField(default=False)),
                ('employee_id', models.CharField(blank=True, max_length=50, null=True)),
                ('shift_hours', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cashiers', to='accounts.provider')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cashier_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
