# Generated by Django 4.2.7 on 2025-09-27 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20250928_0100'),
        ('accounts', '0004_provider_callback_url_provider_mpesa_consumer_key_and_more'),
    ]

    operations = [
    ]
