# Generated by Django 4.2.7 on 2025-09-28 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_merge_20250928_0151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('provider', 'Provider'), ('cashier', 'Cashier/Operator'), ('end_user', 'End User')], default='end_user', max_length=20),
        ),
    ]
