# Generated by Django 4.2.7 on 2025-09-27 21:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_auto_20250928_0059'),
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tickettype',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='ticketusage',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='ticket',
            name='tickets_tic_usernam_a198c2_idx',
        ),
        migrations.RemoveIndex(
            model_name='ticket',
            name='tickets_tic_status_0e5646_idx',
        ),
        migrations.RenameField(
            model_name='ticketusage',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='activated_at',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='data_used_bytes',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='is_synced_to_router',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='mikrotik_profile',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='mikrotik_username',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='time_used_seconds',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='user',
        ),
        migrations.RemoveField(
            model_name='ticketbatch',
            name='generated_at',
        ),
        migrations.RemoveField(
            model_name='ticketbatch',
            name='is_generated',
        ),
        migrations.RemoveField(
            model_name='ticketbatch',
            name='name',
        ),
        migrations.RemoveField(
            model_name='ticketbatch',
            name='password_length',
        ),
        migrations.RemoveField(
            model_name='ticketbatch',
            name='user',
        ),
        migrations.RemoveField(
            model_name='ticketbatch',
            name='username_prefix',
        ),
        migrations.RemoveField(
            model_name='ticketsale',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='ticketsale',
            name='sale_price',
        ),
        migrations.RemoveField(
            model_name='ticketsale',
            name='sold_by',
        ),
        migrations.RemoveField(
            model_name='ticketusage',
            name='data_used_bytes',
        ),
        migrations.RemoveField(
            model_name='ticketusage',
            name='time_used_seconds',
        ),
        migrations.RemoveField(
            model_name='ticketusage',
            name='user_agent',
        ),
        migrations.AddField(
            model_name='ticket',
            name='code',
            field=models.CharField(default='TEMP', max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='currency',
            field=models.CharField(default='KES', max_length=3),
        ),
        migrations.AddField(
            model_name='ticket',
            name='data_used',
            field=models.IntegerField(default=0, help_text='Data used in MB'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='max_data',
            field=models.IntegerField(default=0, help_text='Maximum data in MB'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='max_time',
            field=models.IntegerField(default=0, help_text='Maximum time in minutes'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='ticket',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='accounts.provider'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='time_used',
            field=models.IntegerField(default=0, help_text='Time used in minutes'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='used_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticketbatch',
            name='batch_name',
            field=models.CharField(default='Batch', max_length=100),
        ),
        migrations.AddField(
            model_name='ticketbatch',
            name='end_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ticketbatch',
            name='expiry_days',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='ticketbatch',
            name='generated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='generated_batches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticketbatch',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_batches', to='accounts.provider'),
        ),
        migrations.AddField(
            model_name='ticketbatch',
            name='start_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ticketsale',
            name='currency',
            field=models.CharField(default='KES', max_length=3),
        ),
        migrations.AddField(
            model_name='ticketsale',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_sales', to='accounts.provider'),
        ),
        migrations.AddField(
            model_name='ticketsale',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='ticketsale',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='completed', max_length=20),
        ),
        migrations.AddField(
            model_name='ticketsale',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='ticketsale',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='ticketsale',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tickettype',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_types', to='accounts.provider'),
        ),
        migrations.AddField(
            model_name='tickettype',
            name='value',
            field=models.IntegerField(default=1, help_text='Time in hours or data in GB'),
        ),
        migrations.AddField(
            model_name='ticketusage',
            name='device_info',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='ticketusage',
            name='session_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticketusage',
            name='session_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticketusage',
            name='total_data_consumed',
            field=models.IntegerField(default=0, help_text='Total data consumed in MB'),
        ),
        migrations.AddField(
            model_name='ticketusage',
            name='total_session_time',
            field=models.IntegerField(default=0, help_text='Total session time in minutes'),
        ),
        migrations.AddField(
            model_name='ticketusage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='expires_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ticketbatch',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ticketbatch',
            name='ticket_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='tickets.tickettype'),
        ),
        migrations.AlterField(
            model_name='ticketsale',
            name='customer_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='ticketsale',
            name='customer_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ticketsale',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        # First, remove the old id field
        migrations.RemoveField(
            model_name='ticketsale',
            name='id',
        ),
        # Then add the new id field with correct type
        migrations.AddField(
            model_name='ticketsale',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ticketsale',
            name='payment_method',
            field=models.CharField(default='cash', max_length=50),
        ),
        migrations.AlterField(
            model_name='ticketsale',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ticketsale',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='tickets.ticket'),
        ),
        migrations.AlterField(
            model_name='tickettype',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tickettype',
            name='name',
            field=models.CharField(default='Default Ticket', max_length=100),
        ),
        migrations.AlterField(
            model_name='tickettype',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='tickettype',
            name='ticket_type',
            field=models.CharField(choices=[('time', 'Time-based'), ('data', 'Data-based')], default='time', max_length=10),
        ),
        migrations.AlterField(
            model_name='ticketusage',
            name='ticket',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usage', to='tickets.ticket'),
        ),
        migrations.AlterUniqueTogether(
            name='tickettype',
            unique_together={('provider', 'name')},
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['code'], name='tickets_tic_code_2520cc_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['provider', 'status'], name='tickets_tic_provide_e52035_idx'),
        ),
        migrations.RemoveField(
            model_name='tickettype',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='tickettype',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='tickettype',
            name='data_limit_gb',
        ),
        migrations.RemoveField(
            model_name='tickettype',
            name='duration_hours',
        ),
        migrations.RemoveField(
            model_name='tickettype',
            name='is_popular',
        ),
        migrations.RemoveField(
            model_name='tickettype',
            name='sort_order',
        ),
    ]
